/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spm.timetablemanagement.form.student_details;
import com.spm.timetablemanagement.util.Constant;
import com.spm.timetablemanagement.util.CreateQuery;
import com.spm.timetablemanagement.util.DBconnection;
import static com.spm.timetablemanagement.util.DBconnection.getConnection;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hvdil
 */
public class enterYnS extends javax.swing.JPanel {

    private Connection connection;
    private int yNsId;
    
    /**
     * Creates new form enterYnS
     */
    public enterYnS() {
        
        initComponents();
        //setYnSTableData();
        showYnSList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_YnS = new javax.swing.JTextField();
        btn_addYnS = new javax.swing.JButton();
        btn_deleteYnS = new javax.swing.JButton();
        btn_updateYnS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_yNs = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Enter Academic Year & Semester");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(188, 188, 188))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_YnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_YnSActionPerformed(evt);
            }
        });

        btn_addYnS.setBackground(new java.awt.Color(255, 255, 255));
        btn_addYnS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_addYnS.setForeground(new java.awt.Color(51, 51, 51));
        btn_addYnS.setText("Insert");
        btn_addYnS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addYnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addYnSActionPerformed(evt);
            }
        });

        btn_deleteYnS.setBackground(new java.awt.Color(255, 255, 255));
        btn_deleteYnS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_deleteYnS.setForeground(new java.awt.Color(51, 51, 51));
        btn_deleteYnS.setText("Delete");
        btn_deleteYnS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteYnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteYnSActionPerformed(evt);
            }
        });

        btn_updateYnS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_updateYnS.setText("Update");
        btn_updateYnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateYnSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_YnS, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_addYnS)
                .addGap(38, 38, 38)
                .addComponent(btn_updateYnS)
                .addGap(28, 28, 28)
                .addComponent(btn_deleteYnS)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_YnS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteYnS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addYnS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_updateYnS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        tbl_yNs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Academic Year & Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_yNs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_yNsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_yNs);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 508, Short.MAX_VALUE)))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_YnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_YnSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_YnSActionPerformed

    private void btn_addYnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addYnSActionPerformed
        // TODO add your handling code here:
        
        try{
            DefaultTableModel model = (DefaultTableModel)tbl_yNs.getModel();
            model.addRow(new Object[]{txt_YnS.getText()});
            
            connection = DBconnection.getConnection();   
            PreparedStatement statement = connection.prepareStatement(CreateQuery.getQuery(Constant.INSERT_YEAR_AND_SEMESTER_TABLE));
            statement.setString(1, txt_YnS.getText());
            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "inserting successful");
            connection.close();
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_addYnSActionPerformed

    private void tbl_yNsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_yNsMouseClicked
        // TODO add your handling code here:

        int i = tbl_yNs.getSelectedRow();
        TableModel model = tbl_yNs.getModel();
        txt_YnS.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_tbl_yNsMouseClicked

    private void btn_deleteYnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteYnSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteYnSActionPerformed

    private void btn_updateYnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateYnSActionPerformed
        // TODO add your handling code here:
        int id = 7;

        try
        {
            Statement smt = connection.createStatement();
            smt.execute("UPDATE academic_year_and_semester SET yNs = '"+txt_YnS.getText()+"' WHERE id = "+id); 
            JOptionPane.showMessageDialog(this, "Updated");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_updateYnSActionPerformed

    
    public ArrayList<YnS> getYnSList()
    {
        ArrayList<YnS> list = new ArrayList<YnS>();
        try{
        connection = DBconnection.getConnection();
        String querry = "select * from academic_year_and_semester";
        Statement st;
        ResultSet rs;
        
        st = connection.createStatement();
        rs= st.executeQuery(querry);
        YnS yns;
        while(rs.next())
        {
            yns = new YnS(rs.getInt("id"), rs.getString("yNs"));
            list.add(yns);
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return list;
    }
    
    public void showYnSList()
    {
        ArrayList<YnS> list = getYnSList();
        DefaultTableModel model = (DefaultTableModel)tbl_yNs.getModel();
        Object[] row = new Object[1];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getYnS();
            
            model.addRow(row);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addYnS;
    private javax.swing.JButton btn_deleteYnS;
    private javax.swing.JButton btn_updateYnS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_yNs;
    private javax.swing.JTextField txt_YnS;
    // End of variables declaration//GEN-END:variables

    private void executeSQlQuery(String query,String message) {
        
         try{
        connection = DBconnection.getConnection();
        Statement st;
        
        st = connection.createStatement();
        if ((st.executeUpdate(query)) == 1)
        {
            JOptionPane.showMessageDialog(null, "Data "+message+" Successful");
            
        }else{
            JOptionPane.showMessageDialog(null, "Data Not "+message);
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        } 
    }
}
