/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spm.timetablemanagement.form.student_details;

import com.spm.timetablemanagement.util.Constant;
import com.spm.timetablemanagement.util.CreateQuery;
import com.spm.timetablemanagement.util.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hvdil
 */
public class enterGNo extends javax.swing.JPanel {

    Connection connection;
    /**
     * Creates new form enterGNo
     */
    public enterGNo() {
        initComponents();
        showGNList();
        txt_id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_gNo = new javax.swing.JTextField();
        btn_addGno = new javax.swing.JButton();
        btn_editGn = new javax.swing.JButton();
        btn_deleteGn = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Gn = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Enter Group Number");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(197, 197, 197))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txt_gNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gNoActionPerformed(evt);
            }
        });

        btn_addGno.setBackground(new java.awt.Color(255, 255, 255));
        btn_addGno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_addGno.setForeground(new java.awt.Color(51, 51, 51));
        btn_addGno.setText("Instert");
        btn_addGno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addGno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addGnoActionPerformed(evt);
            }
        });

        btn_editGn.setBackground(new java.awt.Color(255, 255, 255));
        btn_editGn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editGn.setText("Update");
        btn_editGn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editGnActionPerformed(evt);
            }
        });

        btn_deleteGn.setBackground(new java.awt.Color(255, 255, 255));
        btn_deleteGn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_deleteGn.setText("Delete");
        btn_deleteGn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteGnActionPerformed(evt);
            }
        });

        txt_id.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_gNo, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_addGno)
                        .addGap(145, 145, 145)
                        .addComponent(btn_deleteGn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_editGn))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gNo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_addGno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteGn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_editGn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 190));

        tbl_Gn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Group Number"
            }
        ));
        tbl_Gn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_GnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Gn);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 480, 411));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(73, 58, 141, 148);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_gNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gNoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_gNoActionPerformed

    private void btn_addGnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addGnoActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel model = (DefaultTableModel)tbl_Gn.getModel();
            
            connection = DBconnection.getConnection();
            
            PreparedStatement statement = connection.prepareStatement(CreateQuery.getQuery(Constant.INSERT_GROUP_NUMBER_TABLE));
            
            statement.setString(1, txt_gNo.getText());
            
            statement.executeUpdate();
            model.setRowCount(0);
            showGNList();
            txt_gNo.setText("");
            JOptionPane.showMessageDialog(null, "inserting successful");
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_addGnoActionPerformed

    private void tbl_GnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_GnMouseClicked
        // TODO add your handling code here:
        int i = tbl_Gn.getSelectedRow();
        TableModel model = tbl_Gn.getModel();
        txt_id.setText(model.getValueAt(i, 0).toString());
        txt_gNo.setText(model.getValueAt(i, 1).toString());
    }//GEN-LAST:event_tbl_GnMouseClicked

    private void btn_deleteGnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteGnActionPerformed
        // TODO add your handling code here:
        String id = txt_id.getText();

        try
        {
            DefaultTableModel model = (DefaultTableModel)tbl_Gn.getModel();
            Statement smt = connection.createStatement();
            smt.execute("DELETE FROM group_number WHERE id = "+id); 
            model.setRowCount(0);
            showGNList();
            txt_gNo.setText("");
            JOptionPane.showMessageDialog(this, "Deleted");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_deleteGnActionPerformed

    private void btn_editGnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editGnActionPerformed
        // TODO add your handling code here:
        String id = txt_id.getText();

        try
        {
            DefaultTableModel model = (DefaultTableModel)tbl_Gn.getModel();
            Statement smt = connection.createStatement();
            smt.execute("UPDATE group_number SET gNo = '"+txt_gNo.getText()+"' WHERE id = "+id); 
            model.setRowCount(0);
            showGNList();
            txt_gNo.setText("");
            JOptionPane.showMessageDialog(this, "Updated");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_editGnActionPerformed

    public ArrayList<GroupNo> getGNList()
    {
        ArrayList<GroupNo> list = new ArrayList<GroupNo>();
        try{
        connection = DBconnection.getConnection();
        String querry = "select * from group_number";
        Statement st;
        ResultSet rs;
        
        st = connection.createStatement();
        rs= st.executeQuery(querry);
        GroupNo groupN;
        while(rs.next())
        {
            groupN = new GroupNo(rs.getInt("id"), rs.getString("gNo"));
            list.add(groupN);
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return list;
    }
    
    public void showGNList()
    {
        ArrayList<GroupNo> list = getGNList();
        DefaultTableModel model = (DefaultTableModel)tbl_Gn.getModel();
        Object[] row = new Object[2];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getGn();
            
            model.addRow(row);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addGno;
    private javax.swing.JButton btn_deleteGn;
    private javax.swing.JButton btn_editGn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Gn;
    private javax.swing.JTextField txt_gNo;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
