/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spm.timetablemanagement.form.student_details;

import com.spm.timetablemanagement.util.Constant;
import com.spm.timetablemanagement.util.CreateQuery;
import com.spm.timetablemanagement.util.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hvdil
 */
public class groupId_generate extends javax.swing.JPanel {
    
    Connection connection;
    PreparedStatement pst, pst2;
    ResultSet rs;
    /**
     * Creates new form groupId_generate
     */
    public groupId_generate() {
        initComponents();
        yNsSelection();
        dpSelection();
        gNoSelection();
        showGeneratedIdList();
        txt_id.setVisible(false);
        gid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_generate_gId = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        select_yNs = new javax.swing.JComboBox<>();
        select_dp = new javax.swing.JComboBox<>();
        select_gn = new javax.swing.JComboBox<>();
        btn_editGid = new javax.swing.JButton();
        btn_deleteGid = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        gid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_gId = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Academic Year & Semester");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_generate_gId.setBackground(new java.awt.Color(255, 255, 255));
        btn_generate_gId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_generate_gId.setForeground(new java.awt.Color(51, 51, 51));
        btn_generate_gId.setText("Generate");
        btn_generate_gId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generate_gId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generate_gIdActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Degree Program");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(95, 95, 95))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Group Number");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        select_yNs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select"}));
        select_yNs.setToolTipText("");
        select_yNs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_yNsActionPerformed(evt);
            }
        });

        select_dp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        select_dp.setToolTipText("");
        select_dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_dpActionPerformed(evt);
            }
        });

        select_gn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        select_gn.setToolTipText("");
        select_gn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_gnActionPerformed(evt);
            }
        });

        btn_editGid.setBackground(new java.awt.Color(255, 255, 255));
        btn_editGid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editGid.setText("Update");
        btn_editGid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editGidActionPerformed(evt);
            }
        });

        btn_deleteGid.setBackground(new java.awt.Color(255, 255, 255));
        btn_deleteGid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_deleteGid.setText("Delete");
        btn_deleteGid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteGidActionPerformed(evt);
            }
        });

        txt_id.setText("ID");
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        gid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(select_yNs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(select_dp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(select_gn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_generate_gId, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editGid, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_deleteGid, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(select_yNs))
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(select_dp))
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(select_gn)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_generate_gId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_editGid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btn_deleteGid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))))
        );

        tbl_gId.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Group ID"
            }
        ));
        tbl_gId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_gIdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_gId);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 0, 56, 0);
        add(jPanel9, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generate_gIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generate_gIdActionPerformed
        // TODO add your handling code here:
        
        try{
            
            DefaultTableModel model = (DefaultTableModel)tbl_gId.getModel();
            model.addRow(new Object[]{select_yNs.getSelectedItem().toString()+"."+select_dp.getSelectedItem().toString()+"."+select_gn.getSelectedItem().toString()});
            
            connection = DBconnection.getConnection();
            
            pst = connection.prepareStatement(CreateQuery.getQuery(Constant.INSERT_GROUP_ID_TABLE));
            
            pst2 = connection.prepareStatement(CreateQuery.getQuery(Constant.INSERT_ALL_DETAILS_TABLE));
            
            String generateID = (select_yNs.getSelectedItem().toString()+"."+select_dp.getSelectedItem().toString()+"."+select_gn.getSelectedItem().toString());
            
            pst.setString(1, generateID);
            
            pst2.setString(1, select_yNs.getSelectedItem().toString());
            pst2.setString(2, select_dp.getSelectedItem().toString());
            pst2.setString(3, generateID);
            pst2.setString(4, "-");
            
            pst.executeUpdate();
            pst2.executeUpdate();
            model.setRowCount(0);
            showGeneratedIdList();
            JOptionPane.showMessageDialog(null, "inserting successful");
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_generate_gIdActionPerformed

    private void select_yNsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_yNsActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_select_yNsActionPerformed

    private void select_dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_dpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_dpActionPerformed

    private void select_gnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_gnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_gnActionPerformed

    private void tbl_gIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_gIdMouseClicked
        // TODO add your handling code here:
        int i = tbl_gId.getSelectedRow();
        TableModel model = tbl_gId.getModel();
        txt_id.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_tbl_gIdMouseClicked

    private void btn_deleteGidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteGidActionPerformed
        // TODO add your handling code here:
        String id = txt_id.getText();

        try
        {
            int i = tbl_gId.getSelectedRow();
            TableModel mt = tbl_gId.getModel();
            gid.setText(mt.getValueAt(i, 1).toString());
            
            DefaultTableModel model = (DefaultTableModel)tbl_gId.getModel();
            Statement smt = connection.createStatement();
            smt.execute("DELETE FROM generated_group_id WHERE id = "+id);
            smt.execute("DELETE FROM all_details WHERE gId = '"+gid.getText().toString()+"' AND sGid = '-' ");
            model.setRowCount(0);
            showGeneratedIdList();
            JOptionPane.showMessageDialog(this, "Deleted");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_deleteGidActionPerformed

    private void btn_editGidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editGidActionPerformed
        // TODO add your handling code here:
        String id = txt_id.getText();
        String newGenerateID = (select_yNs.getSelectedItem().toString()+"."+select_dp.getSelectedItem().toString()+"."+select_gn.getSelectedItem().toString());

        try
        {
            int i = tbl_gId.getSelectedRow();
            TableModel mt = tbl_gId.getModel();
            gid.setText(mt.getValueAt(i, 1).toString());
            
            DefaultTableModel model = (DefaultTableModel)tbl_gId.getModel();
            Statement smt = connection.createStatement();
            smt.execute("UPDATE generated_group_id SET gId = '"+newGenerateID+"' WHERE id = "+id);
            smt.execute("UPDATE all_details SET gId = '"+newGenerateID+"' WHERE gId = '"+gid.getText().toString()+"' AND sGid = '-' ");
            model.setRowCount(0);
            showGeneratedIdList();
            JOptionPane.showMessageDialog(this, "Updated");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_editGidActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void gidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gidActionPerformed

    public  void yNsSelection(){
        try{  
        connection = DBconnection.getConnection();
        String query = "select * from academic_year_and_semester";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String yNs = rs.getString("yNs");
            select_yNs.addItem(yNs);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public  void dpSelection(){
        try{  
        connection = DBconnection.getConnection();
        String query = "select * from degree_program";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String dp = rs.getString("dp");
            select_dp.addItem(dp);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public  void gNoSelection(){
        try{  
        connection = DBconnection.getConnection();
        String query = "select * from group_number";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String gNo = rs.getString("gNo");
            select_gn.addItem(gNo);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public ArrayList<GeneratedId> GetGeneratedIdList()
    {
        ArrayList<GeneratedId> list = new ArrayList<GeneratedId>();
        try{
        connection = DBconnection.getConnection();
        String querry = "select * from generated_group_id";
        Statement st;
        ResultSet rs;
        
        st = connection.createStatement();
        rs= st.executeQuery(querry);
        GeneratedId GID;
        while(rs.next())
        {
            GID = new GeneratedId(rs.getInt("id"), rs.getString("gId"));
            list.add(GID);
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return list;
    }
    
    public void showGeneratedIdList()
    {
        ArrayList<GeneratedId> list = GetGeneratedIdList();
        DefaultTableModel model = (DefaultTableModel)tbl_gId.getModel();
        Object[] row = new Object[2];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getGid();
            
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deleteGid;
    private javax.swing.JButton btn_editGid;
    private javax.swing.JButton btn_generate_gId;
    private javax.swing.JTextField gid;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> select_dp;
    private javax.swing.JComboBox<String> select_gn;
    private javax.swing.JComboBox<String> select_yNs;
    private javax.swing.JTable tbl_gId;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
