/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spm.timetablemanagement.form.student_details;

import com.spm.timetablemanagement.util.Constant;
import com.spm.timetablemanagement.util.CreateQuery;
import com.spm.timetablemanagement.util.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hvdil
 */
public class sub_GroupId_generate extends javax.swing.JPanel {

    Connection connection;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form sub_GroupId_generate
     */
    public sub_GroupId_generate() {
        initComponents();
        gIdSelection();
        sGnoSelection();
        showGeneratedSubIdList();
        txt_id.setVisible(false);
        sgid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btn_generate_sGid = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        select_gId = new javax.swing.JComboBox<>();
        select_sGno = new javax.swing.JComboBox<>();
        btn_edit_sGid = new javax.swing.JButton();
        btn_delete_sGid = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sGid = new javax.swing.JTable();
        sgid = new javax.swing.JTextField();

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));

        btn_generate_sGid.setBackground(new java.awt.Color(255, 255, 255));
        btn_generate_sGid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_generate_sGid.setForeground(new java.awt.Color(51, 51, 51));
        btn_generate_sGid.setText("Generate");
        btn_generate_sGid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generate_sGid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generate_sGidActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Group ID");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(114, 114, 114))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Sub-Group Number");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(87, 87, 87))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        select_gId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        select_gId.setToolTipText("");
        select_gId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_gIdActionPerformed(evt);
            }
        });

        select_sGno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        select_sGno.setToolTipText("");
        select_sGno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_sGnoActionPerformed(evt);
            }
        });

        btn_edit_sGid.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit_sGid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_edit_sGid.setText("Update");
        btn_edit_sGid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_sGidActionPerformed(evt);
            }
        });

        btn_delete_sGid.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete_sGid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete_sGid.setText("Delete");
        btn_delete_sGid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_sGidActionPerformed(evt);
            }
        });

        txt_id.setText("ID");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(select_gId, 0, 83, Short.MAX_VALUE)
                            .addComponent(select_sGno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btn_generate_sGid)
                        .addGap(32, 32, 32)
                        .addComponent(btn_edit_sGid, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_delete_sGid, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(select_gId))
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(select_sGno)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_generate_sGid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit_sGid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete_sGid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 11, -1, 200));

        tbl_sGid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Sub-Group ID"
            }
        ));
        tbl_sGid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sGidMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sGid);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 440, 340));

        sgid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(sgid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(652, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(sgid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generate_sGidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generate_sGidActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel model = (DefaultTableModel)tbl_sGid.getModel();
            model.addRow(new Object[]{select_gId.getSelectedItem().toString()+"."+select_sGno.getSelectedItem().toString()});
            
            Connection connection = DBconnection.getConnection();

            PreparedStatement statement = connection.prepareStatement(CreateQuery.getQuery(Constant.INSERT_SUB_GROUP_ID_TABLE));
            
            String generateSID = (select_gId.getSelectedItem().toString()+"."+select_sGno.getSelectedItem().toString());
            statement.setString(1, generateSID);
            statement.executeUpdate();
            model.setRowCount(0);
            statement.close();

            String selectedGid = select_gId.getSelectedItem().toString();
            Statement smt = connection.createStatement();
            smt.execute("UPDATE all_details SET sGid = '"+generateSID+"' WHERE gId = '"+selectedGid+"'");

            showGeneratedSubIdList();
            JOptionPane.showMessageDialog(null, "inserting successful");
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_generate_sGidActionPerformed

    private void select_gIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_gIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_gIdActionPerformed

    private void select_sGnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_sGnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_sGnoActionPerformed

    private void tbl_sGidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sGidMouseClicked
        // TODO add your handling code here:
        int i = tbl_sGid.getSelectedRow();
        TableModel model = tbl_sGid.getModel();
        txt_id.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_tbl_sGidMouseClicked

    private void btn_delete_sGidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_sGidActionPerformed
        // TODO add your handling code here:
        String id = txt_id.getText();

        try
        {
            int i = tbl_sGid.getSelectedRow();
            TableModel mt = tbl_sGid.getModel();
            sgid.setText(mt.getValueAt(i, 1).toString());
            
            DefaultTableModel model = (DefaultTableModel)tbl_sGid.getModel();
            Statement smt = connection.createStatement();
            smt.execute("DELETE FROM generated_sub_group_id WHERE id = "+id);
            smt.execute("DELETE FROM all_details WHERE sGid = "+sgid.getText().toString());
            model.setRowCount(0);
            showGeneratedSubIdList();
            JOptionPane.showMessageDialog(this, "Deleted");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_delete_sGidActionPerformed

    private void btn_edit_sGidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_sGidActionPerformed
        // TODO add your handling code here:
        String id = txt_id.getText();
        String newGenerateID = (select_gId.getSelectedItem().toString()+"."+select_sGno.getSelectedItem().toString());

        try
        {
            int i = tbl_sGid.getSelectedRow();
            TableModel mt = tbl_sGid.getModel();
            sgid.setText(mt.getValueAt(i, 1).toString());
            
            DefaultTableModel model = (DefaultTableModel)tbl_sGid.getModel();
            Statement smt = connection.createStatement();
            smt.execute("UPDATE generated_sub_group_id SET sGid = '"+newGenerateID+"' WHERE id = "+id); 
            smt.execute("UPDATE all_details SET sGid = '"+newGenerateID+"' WHERE sGid = '"+sgid.getText().toString()+"'");
            model.setRowCount(0);
            showGeneratedSubIdList();
            JOptionPane.showMessageDialog(this, "Updated");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_edit_sGidActionPerformed

    private void sgidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgidActionPerformed

    public  void gIdSelection(){
        try{  
        connection = DBconnection.getConnection();
        String query = "select * from generated_group_id";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String gId = rs.getString("gId");
            select_gId.addItem(gId);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public  void sGnoSelection(){
        try{  
        connection = DBconnection.getConnection();
        String query = "select * from sub_group_number";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String sGno = rs.getString("sGno");
            select_sGno.addItem(sGno);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public ArrayList<GeneratedSubId> GetGeneratedSubIdList()
    {
        ArrayList<GeneratedSubId> list = new ArrayList<GeneratedSubId>();
        try{
        connection = DBconnection.getConnection();
        String querry = "select * from generated_sub_group_id";
        Statement st;
        ResultSet rs;
        
        st = connection.createStatement();
        rs= st.executeQuery(querry);
        GeneratedSubId SGID;
        while(rs.next())
        {
            SGID = new GeneratedSubId(rs.getInt("id"), rs.getString("sGid"));
            list.add(SGID);
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return list;
    }
    
    public void showGeneratedSubIdList()
    {
        ArrayList<GeneratedSubId> list = GetGeneratedSubIdList();
        DefaultTableModel model = (DefaultTableModel)tbl_sGid.getModel();
        Object[] row = new Object[2];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getSgId();
            
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete_sGid;
    private javax.swing.JButton btn_edit_sGid;
    private javax.swing.JButton btn_generate_sGid;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> select_gId;
    private javax.swing.JComboBox<String> select_sGno;
    private javax.swing.JTextField sgid;
    private javax.swing.JTable tbl_sGid;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
