/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spm.timetablemanagement.form.student_details;

import com.spm.timetablemanagement.util.DBconnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hvdil
 */
public class view_All_Details extends javax.swing.JPanel {

    private Connection connection;
    /**
     * Creates new form view_All_Details
     */
    public view_All_Details() {
        initComponents();
        showAllList();
    }

    public ArrayList<AllDetails> getAllList()
    {
        ArrayList<AllDetails> list = new ArrayList<AllDetails>();
        try{
        connection = DBconnection.getConnection();
        String querry = "select * from all_details";
        Statement st;
        ResultSet rs;
        
        st = connection.createStatement();
        rs= st.executeQuery(querry);
        AllDetails all;
        while(rs.next())
        {
            all = new AllDetails(rs.getInt("id"), rs.getString("yNs"), rs.getString("dp"), rs.getString("gId"), rs.getString("sGid"));
            list.add(all);
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return list;
    }
    
    public void showAllList()
    {
        ArrayList<AllDetails> list = getAllList();
        DefaultTableModel model = (DefaultTableModel)tbl_viewAll.getModel();
        Object[] row = new Object[4];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getyNs();
            row[1] = list.get(i).getdp();
            row[2] = list.get(i).getGid();
            row[3] = list.get(i).getSgId();

            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_viewAll = new javax.swing.JTable();

        tbl_viewAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Academic Year & Semester", "Degree Program", "Group ID", "Sub-Group ID"
            }
        ));
        jScrollPane1.setViewportView(tbl_viewAll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_viewAll;
    // End of variables declaration//GEN-END:variables
}
